name: qivi_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  json_serializable: ^6.3.1
  flutter_bloc: ^8.0.1
  built_value: ^8.4.0
  equatable: ^2.0.3
  flutter_svg: ^1.1.1+1
  cupertino_icons: ^1.0.2
  logger: ^1.1.0
  font_awesome_flutter: ^10.1.0
  
  persistent_bottom_nav_bar: ^4.0.2
  flutter_native_splash: ^2.2.6
  connectivity_plus: ^2.3.6
  carousel_slider: ^4.1.1
  gql_http_link: ^0.4.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.6.0
  path_provider: any
  gql_build: ^0.4.2-alpha+1659554286830
  graphql: ^5.1.1
  uuid: ^3.0.6
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.2.0
flutter:
  uses-material-design: true
  assets:
    - assets/logo-qivi.png
    - assets/images/
